public  class ContactTriggerHanler {
    public static void validateLead(List<Contact> accTriggerNew,List<Contact> accTriggerOld,Map<id, Contact> accTriggerNewMap, Map<id, Contact> accTriggerOldmap){
        //if leadsources is already partner refferal do not allwo user to update any record
        //adderror method to add validation or throw error in trigger
             // we can use add error method in one record of trigger . new or newmap
             //
        
    }
}