public class MapDemo {
    public static void mapPrac(){
        Map<String,Integer> mp1=new map<String,Integer>();
        mp1.put('person_id_1',1);
        mp1.put('person_id_1',1);
        mp1.put('person_id_2',5);
        mp1.put('person_id_3',6);
        mp1.put('',6);
        mp1.put('person_id_3',null);
        //if key is diplicated it will be overeride
        System.debug(mp1);
    }
        


         
}